# Generated by Django 5.2.7 on 2025-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worldcities',
            fields=[
                ('city', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'worldcities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
    ]
